namespace PicoBench.Formatters;

/// <summary>
/// Formats benchmark results as HTML with embedded CSS styling.
/// No external dependencies required.
/// </summary>
public sealed class HtmlFormatter(FormatterOptions? options = null) : FormatterBase(options)
{
    /// <inheritdoc />
    protected override string FormatCore(IEnumerable<BenchmarkResult> results)
    {
        var sb = new StringBuilder();
        var list = results.ToList();

        AppendHtmlHeader(sb, "Benchmark Results");
        sb.AppendLine("<body>");
        sb.AppendLine("<div class=\"container\">");
        sb.AppendLine("<h1>Benchmark Results</h1>");

        if (list.Count == 0)
        {
            sb.AppendLine("<p class=\"no-data\">No results available.</p>");
        }
        else
        {
            AppendResultsTable(sb, list);
        }

        sb.AppendLine("</div>");
        AppendHtmlFooter(sb);

        return sb.ToString();
    }

    /// <inheritdoc />
    protected override string FormatCore(IEnumerable<ComparisonResult> comparisons)
    {
        var sb = new StringBuilder();
        var list = comparisons.ToList();

        AppendHtmlHeader(sb, "Benchmark Comparison");
        sb.AppendLine("<body>");
        sb.AppendLine("<div class=\"container\">");
        sb.AppendLine("<h1>Benchmark Comparison</h1>");

        if (list.Count == 0)
        {
            sb.AppendLine("<p class=\"no-data\">No comparison results available.</p>");
        }
        else
        {
            AppendComparisonSummary(sb, list);
            AppendComparisonsTable(sb, list);
        }

        sb.AppendLine("</div>");
        AppendHtmlFooter(sb);

        return sb.ToString();
    }

    /// <inheritdoc />
    protected override string FormatCore(BenchmarkSuite suite)
    {
        var sb = new StringBuilder();

        AppendHtmlHeader(sb, suite.Name);
        sb.AppendLine("<body>");
        sb.AppendLine("<div class=\"container\">");

        // Header
        sb.AppendLine($"<h1>{Escape(suite.Name)}</h1>");

        if (!string.IsNullOrEmpty(suite.Description))
        {
            sb.AppendLine($"<p class=\"description\">{Escape(suite.Description!)}</p>");
        }

        // Environment info
        if (Options.IncludeEnvironment)
        {
            sb.AppendLine("<div class=\"environment\">");
            sb.AppendLine($"<strong>Environment:</strong> {Escape(suite.Environment.ToString())}");
            sb.AppendLine("</div>");
        }

        if (Options.IncludeTimestamp)
        {
            sb.AppendLine("<div class=\"metadata\">");
            sb.AppendLine(
                $"<span><strong>Timestamp:</strong> {suite.Timestamp:yyyy-MM-dd HH:mm:ss} UTC</span>"
            );
            sb.AppendLine(
                $"<span><strong>Duration:</strong> {suite.Duration.TotalSeconds:F2}s</span>"
            );
            sb.AppendLine("</div>");
        }

        // Comparisons summary and table
        if (suite.Comparisons?.Count > 0)
        {
            sb.AppendLine("<h2>Comparison Summary</h2>");
            AppendComparisonSummary(sb, suite.Comparisons.ToList());

            sb.AppendLine("<h2>Detailed Comparisons</h2>");
            AppendComparisonsTable(sb, suite.Comparisons.ToList());
        }

        // Results table
        if (suite.Results.Count > 0)
        {
            sb.AppendLine("<h2>All Results</h2>");
            AppendResultsTable(sb, suite.Results.ToList());
        }

        sb.AppendLine("</div>");
        AppendHtmlFooter(sb);

        return sb.ToString();
    }

    #region HTML Structure

    private static void AppendHtmlHeader(StringBuilder sb, string title)
    {
        sb.AppendLine("<!DOCTYPE html>");
        sb.AppendLine("<html lang=\"en\">");
        sb.AppendLine("<head>");
        sb.AppendLine("<meta charset=\"UTF-8\">");
        sb.AppendLine("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
        sb.AppendLine($"<title>{Escape(title)}</title>");
        AppendStyles(sb);
        sb.AppendLine("</head>");
    }

    private static void AppendHtmlFooter(StringBuilder sb)
    {
        sb.AppendLine("<footer>");
        sb.AppendLine(
            $"<p>Generated by PicoBench at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC</p>"
        );
        sb.AppendLine("</footer>");
        sb.AppendLine("</body>");
        sb.AppendLine("</html>");
    }

    private static void AppendStyles(StringBuilder sb)
    {
        sb.AppendLine("<style>");
        sb.AppendLine(
            @"
:root {
    --primary: #2563eb;
    --success: #16a34a;
    --warning: #ea580c;
    --danger: #dc2626;
    --bg: #f8fafc;
    --card-bg: #ffffff;
    --text: #1e293b;
    --text-muted: #64748b;
    --border: #e2e8f0;
}

* {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}

body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
    background: var(--bg);
    color: var(--text);
    line-height: 1.6;
    padding: 2rem;
}

.container {
    max-width: 1200px;
    margin: 0 auto;
}

h1 {
    font-size: 2rem;
    margin-bottom: 1rem;
    color: var(--primary);
}

h2 {
    font-size: 1.5rem;
    margin: 2rem 0 1rem;
    color: var(--text);
    border-bottom: 2px solid var(--border);
    padding-bottom: 0.5rem;
}

.description {
    color: var(--text-muted);
    margin-bottom: 1rem;
}

.environment, .metadata {
    background: var(--card-bg);
    border: 1px solid var(--border);
    border-radius: 0.5rem;
    padding: 1rem;
    margin-bottom: 1rem;
    font-size: 0.875rem;
}

.metadata {
    display: flex;
    gap: 2rem;
    flex-wrap: wrap;
}

.summary-box {
    background: linear-gradient(135deg, var(--primary) 0%, #1d4ed8 100%);
    color: white;
    border-radius: 0.75rem;
    padding: 1.5rem;
    margin-bottom: 2rem;
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 1rem;
}

.summary-item {
    text-align: center;
}

.summary-item .value {
    font-size: 2rem;
    font-weight: 700;
}

.summary-item .label {
    font-size: 0.875rem;
    opacity: 0.9;
}

table {
    width: 100%;
    border-collapse: collapse;
    background: var(--card-bg);
    border-radius: 0.5rem;
    overflow: hidden;
    box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    margin-bottom: 2rem;
}

th, td {
    padding: 0.75rem 1rem;
    text-align: left;
    border-bottom: 1px solid var(--border);
}

th {
    background: var(--bg);
    font-weight: 600;
    font-size: 0.875rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: var(--text-muted);
}

tr:hover {
    background: #f1f5f9;
}

tr:last-child td {
    border-bottom: none;
}

.number {
    text-align: right;
    font-variant-numeric: tabular-nums;
}

.speedup {
    font-weight: 600;
    padding: 0.25rem 0.5rem;
    border-radius: 0.25rem;
    display: inline-block;
    min-width: 4rem;
    text-align: center;
}

.speedup.fast { background: #dcfce7; color: var(--success); }
.speedup.very-fast { background: #bbf7d0; color: #15803d; }
.speedup.slow { background: #fee2e2; color: var(--danger); }
.speedup.neutral { background: #f1f5f9; color: var(--text-muted); }

.indicator {
    font-size: 1.25rem;
    margin-left: 0.5rem;
}

.gc-info {
    font-size: 0.75rem;
    color: var(--text-muted);
    font-family: monospace;
}

.no-data {
    text-align: center;
    color: var(--text-muted);
    padding: 2rem;
}

footer {
    margin-top: 3rem;
    padding-top: 1rem;
    border-top: 1px solid var(--border);
    text-align: center;
    font-size: 0.75rem;
    color: var(--text-muted);
}

@media (max-width: 768px) {
    body { padding: 1rem; }
    h1 { font-size: 1.5rem; }
    table { font-size: 0.875rem; }
    th, td { padding: 0.5rem; }
    .summary-box { grid-template-columns: 1fr 1fr; }
}
"
        );
        sb.AppendLine("</style>");
    }

    #endregion

    #region Results Table

    private void AppendResultsTable(StringBuilder sb, List<BenchmarkResult> results)
    {
        sb.AppendLine("<table>");
        sb.AppendLine("<thead><tr>");
        sb.AppendLine("<th>Name</th>");
        sb.AppendLine("<th class=\"number\">Avg (ns)</th>");
        sb.AppendLine("<th class=\"number\">P50 (ns)</th>");

        if (Options.IncludePercentiles)
        {
            sb.AppendLine("<th class=\"number\">P90 (ns)</th>");
            sb.AppendLine("<th class=\"number\">P95 (ns)</th>");
            sb.AppendLine("<th class=\"number\">P99 (ns)</th>");
        }

        if (Options.IncludeCpuCycles)
        {
            sb.AppendLine("<th class=\"number\">CPU Cycles</th>");
        }

        if (Options.IncludeGcInfo)
        {
            sb.AppendLine("<th>GC (0/1/2)</th>");
        }

        sb.AppendLine("</tr></thead>");
        sb.AppendLine("<tbody>");

        foreach (var result in results)
        {
            var s = result.Statistics;
            sb.AppendLine("<tr>");
            sb.AppendLine($"<td>{Escape(result.Name)}</td>");
            sb.AppendLine($"<td class=\"number\">{FormatTime(s.Avg)}</td>");
            sb.AppendLine($"<td class=\"number\">{FormatTime(s.P50)}</td>");

            if (Options.IncludePercentiles)
            {
                sb.AppendLine($"<td class=\"number\">{FormatTime(s.P90)}</td>");
                sb.AppendLine($"<td class=\"number\">{FormatTime(s.P95)}</td>");
                sb.AppendLine($"<td class=\"number\">{FormatTime(s.P99)}</td>");
            }

            if (Options.IncludeCpuCycles)
            {
                sb.AppendLine($"<td class=\"number\">{s.CpuCyclesPerOp:F0}</td>");
            }

            if (Options.IncludeGcInfo)
            {
                sb.AppendLine($"<td class=\"gc-info\">{FormatGcInfo(s.GcInfo)}</td>");
            }

            sb.AppendLine("</tr>");
        }

        sb.AppendLine("</tbody>");
        sb.AppendLine("</table>");
    }

    #endregion

    #region Comparisons

    private static void AppendComparisonSummary(
        StringBuilder sb,
        List<ComparisonResult> comparisons
    )
    {
        var wins = comparisons.Count(c => c.IsFaster);
        var total = comparisons.Count;
        var avgSpeedup = comparisons.Average(c => c.Speedup);
        var maxSpeedup = comparisons.Max(c => c.Speedup);

        sb.AppendLine("<div class=\"summary-box\">");

        sb.AppendLine("<div class=\"summary-item\">");
        sb.AppendLine($"<div class=\"value\">{wins} / {total}</div>");
        sb.AppendLine("<div class=\"label\">Scenarios Won</div>");
        sb.AppendLine("</div>");

        sb.AppendLine("<div class=\"summary-item\">");
        sb.AppendLine($"<div class=\"value\">{avgSpeedup:F2}x</div>");
        sb.AppendLine("<div class=\"label\">Average Speedup</div>");
        sb.AppendLine("</div>");

        sb.AppendLine("<div class=\"summary-item\">");
        sb.AppendLine($"<div class=\"value\">{maxSpeedup:F2}x</div>");
        sb.AppendLine("<div class=\"label\">Maximum Speedup</div>");
        sb.AppendLine("</div>");

        sb.AppendLine("</div>");
    }

    private void AppendComparisonsTable(StringBuilder sb, List<ComparisonResult> comparisons)
    {
        // Flatten to rows with Provider column
        var rows =
            new List<(string TestCase, string Provider, Statistics Stats, double? Speedup)>();
        foreach (var c in comparisons)
        {
            rows.Add((c.Name, Options.CandidateLabel, c.Candidate.Statistics, c.Speedup));
            rows.Add((c.Name, Options.BaselineLabel, c.Baseline.Statistics, null));
        }

        sb.AppendLine("<table>");
        sb.AppendLine("<thead><tr>");
        sb.AppendLine("<th>Test Case</th>");
        sb.AppendLine("<th class=\"number\">Avg (ns)</th>");
        sb.AppendLine("<th class=\"number\">Speedup</th>");

        if (Options.IncludePercentiles)
        {
            sb.AppendLine("<th class=\"number\">P50</th>");
            sb.AppendLine("<th class=\"number\">P90</th>");
            sb.AppendLine("<th class=\"number\">P99</th>");
        }

        if (Options.IncludeCpuCycles)
        {
            sb.AppendLine("<th class=\"number\">CPU</th>");
        }

        if (Options.IncludeGcInfo)
        {
            sb.AppendLine("<th>GC</th>");
        }

        sb.AppendLine("</tr></thead>");
        sb.AppendLine("<tbody>");

        foreach (var row in rows)
        {
            var testCase = $"{row.Provider} * {row.TestCase}";
            var speedupClass = row.Speedup.HasValue ? GetSpeedupClass(row.Speedup.Value) : "";
            var indicator = row.Speedup.HasValue ? GetSpeedupIndicator(row.Speedup.Value) : "";
            var speedupText = row.Speedup.HasValue
                ? $"<span class=\"speedup {speedupClass}\">{FormatSpeedup(row.Speedup.Value)}</span><span class=\"indicator\">{indicator}</span>"
                : "";

            sb.AppendLine("<tr>");
            sb.AppendLine($"<td>{Escape(testCase)}</td>");
            sb.AppendLine($"<td class=\"number\">{FormatTime(row.Stats.Avg)}</td>");
            sb.AppendLine($"<td class=\"number\">{speedupText}</td>");

            if (Options.IncludePercentiles)
            {
                sb.AppendLine($"<td class=\"number\">{FormatTime(row.Stats.P50)}</td>");
                sb.AppendLine($"<td class=\"number\">{FormatTime(row.Stats.P90)}</td>");
                sb.AppendLine($"<td class=\"number\">{FormatTime(row.Stats.P99)}</td>");
            }

            if (Options.IncludeCpuCycles)
            {
                sb.AppendLine($"<td class=\"number\">{row.Stats.CpuCyclesPerOp:F0}</td>");
            }

            if (Options.IncludeGcInfo)
            {
                sb.AppendLine($"<td class=\"gc-info\">{FormatGcInfo(row.Stats.GcInfo)}</td>");
            }

            sb.AppendLine("</tr>");
        }

        sb.AppendLine("</tbody>");
        sb.AppendLine("</table>");
    }

    private static string GetSpeedupClass(double speedup)
    {
        return speedup switch
        {
            >= 3 => "very-fast",
            >= 1.5 => "fast",
            >= 1 => "neutral",
            _ => "slow"
        };
    }

    #endregion

    #region Helpers

    private static string Escape(string value)
    {
        return value
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;")
            .Replace("\"", "&quot;")
            .Replace("'", "&#39;");
    }

    #endregion

    #region Static Helpers

    /// <summary>
    /// Write HTML to a file, creating directory if needed.
    /// </summary>
    public static void WriteToFile(
        string filePath,
        BenchmarkResult result,
        FormatterOptions? options = null
    )
    {
        var formatter = new HtmlFormatter(options);
        WriteToFileInternal(filePath, formatter.Format(result));
    }

    /// <summary>
    /// Write HTML to a file, creating directory if needed.
    /// </summary>
    public static void WriteToFile(
        string filePath,
        IEnumerable<BenchmarkResult> results,
        FormatterOptions? options = null
    )
    {
        var formatter = new HtmlFormatter(options);
        WriteToFileInternal(filePath, formatter.Format(results));
    }

    /// <summary>
    /// Write HTML to a file, creating directory if needed.
    /// </summary>
    public static void WriteToFile(
        string filePath,
        IEnumerable<ComparisonResult> comparisons,
        FormatterOptions? options = null
    )
    {
        var formatter = new HtmlFormatter(options);
        WriteToFileInternal(filePath, formatter.Format(comparisons));
    }

    /// <summary>
    /// Write HTML to a file, creating directory if needed.
    /// </summary>
    public static void WriteToFile(
        string filePath,
        BenchmarkSuite suite,
        FormatterOptions? options = null
    )
    {
        var formatter = new HtmlFormatter(options);
        WriteToFileInternal(filePath, formatter.Format(suite));
    }

    #endregion
}
