namespace PicoBench.Tests.Generators;

public class EmitterTests
{
    // ─── Helper: build a minimal model ──────────────────────────────

    private static BenchmarkClassModel MinimalModel(
        string className = "TestBenchmarks",
        string? ns = null,
        string accessModifier = "public",
        string? description = null,
        LifecycleMethodInfo? globalSetup = null,
        LifecycleMethodInfo? globalCleanup = null,
        LifecycleMethodInfo? iterSetup = null,
        LifecycleMethodInfo? iterCleanup = null,
        bool isAsync = false,
        ImmutableArray<BenchmarkMethodModel>? methods = null,
        ImmutableArray<ParamsPropertyModel>? paramsProps = null
    )
    {
        return new BenchmarkClassModel
        {
            Namespace = ns,
            ClassName = className,
            AccessModifier = accessModifier,
            Description = description,
            IsAsync = isAsync,
            GlobalSetupMethod = globalSetup,
            GlobalCleanupMethod = globalCleanup,
            IterationSetupMethod = iterSetup,
            IterationCleanupMethod = iterCleanup,
            Methods =
                methods
                ?? ImmutableArray.Create(
                    new BenchmarkMethodModel { Name = "DoWork", IsBaseline = false }
                ),
            ParamsProperties = paramsProps ?? ImmutableArray<ParamsPropertyModel>.Empty,
        };
    }

    // ─── Basic generation ───────────────────────────────────────────

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_MinimalModel_ContainsAutoGeneratedHeader()
    {
        var code = Emitter.Generate(MinimalModel());

        await Assert.That(code).Contains("// <auto-generated/>");
        await Assert.That(code).Contains("Generated by PicoBench.Generators");
    }

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_MinimalModel_ImplementsIBenchmarkClass()
    {
        var code = Emitter.Generate(MinimalModel());

        await Assert
            .That(code)
            .Contains("partial class TestBenchmarks : global::PicoBench.IBenchmarkClass");
    }

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_MinimalModel_ContainsRunBenchmarksMethod()
    {
        var code = Emitter.Generate(MinimalModel());

        await Assert.That(code).Contains("RunBenchmarksAsync(");
    }

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_MinimalModel_DefaultsToDefaultConfig()
    {
        var code = Emitter.Generate(MinimalModel());

        await Assert.That(code).Contains("config ??= global::PicoBench.BenchmarkConfig.Default;");
    }

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_MinimalModel_ReturnsBenchmarkSuite()
    {
        var code = Emitter.Generate(MinimalModel());

        await Assert.That(code).Contains("var __suite = new global::PicoBench.BenchmarkSuite(");
        await Assert.That(code).Contains("ValueTask.FromResult(__suite)");
    }

    // ─── Namespace handling ─────────────────────────────────────────

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_WithNamespace_WrapsInNamespaceBlock()
    {
        var code = Emitter.Generate(MinimalModel(ns: "MyApp.Benchmarks"));

        await Assert.That(code).Contains("namespace MyApp.Benchmarks");
    }

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_WithoutNamespace_NoNamespaceBlock()
    {
        var code = Emitter.Generate(MinimalModel(ns: null));

        await Assert.That(code).DoesNotContain("namespace ");
    }

    // ─── Access modifier ────────────────────────────────────────────

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_InternalClass_UsesInternalModifier()
    {
        var code = Emitter.Generate(MinimalModel(accessModifier: "internal"));

        await Assert.That(code).Contains("internal partial class TestBenchmarks");
    }

    // ─── Description ────────────────────────────────────────────────

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_WithDescription_IncludesDescriptionInSuite()
    {
        var code = Emitter.Generate(MinimalModel(description: "My test suite"));

        await Assert.That(code).Contains("description: \"My test suite\"");
    }

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_WithoutDescription_UsesNull()
    {
        var code = Emitter.Generate(MinimalModel(description: null));

        await Assert.That(code).Contains("description: null");
    }

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_DescriptionWithSpecialChars_EscapesCorrectly()
    {
        var code = Emitter.Generate(MinimalModel(description: "Test \"quoted\" suite"));

        await Assert.That(code).Contains("description: \"Test \\\"quoted\\\" suite\"");
    }

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_DescriptionWithControlChar_EscapesAsUnicode()
    {
        var code = Emitter.Generate(MinimalModel(description: "a" + (char)0x01 + "b"));

        await Assert.That(code).Contains("\\u0001");
    }

    // ─── Benchmark methods ──────────────────────────────────────────

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_SingleMethod_CallsBenchmarkRun()
    {
        var code = Emitter.Generate(MinimalModel());

        await Assert.That(code).Contains("Benchmark.Run(\"DoWork\"");
        await Assert.That(code).Contains("this.DoWork()");
    }

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_MultipleMethods_RunsAll()
    {
        var methods = ImmutableArray.Create(
            new BenchmarkMethodModel { Name = "MethodA", IsBaseline = false },
            new BenchmarkMethodModel { Name = "MethodB", IsBaseline = false }
        );
        var code = Emitter.Generate(MinimalModel(methods: methods));

        await Assert.That(code).Contains("this.MethodA()");
        await Assert.That(code).Contains("this.MethodB()");
        await Assert.That(code).Contains("__results.Add(__r_MethodA)");
        await Assert.That(code).Contains("__results.Add(__r_MethodB)");
    }

    // ─── Baseline + Comparisons ─────────────────────────────────────

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_WithBaseline_GeneratesComparisons()
    {
        var methods = ImmutableArray.Create(
            new BenchmarkMethodModel { Name = "BaseMethod", IsBaseline = true },
            new BenchmarkMethodModel { Name = "FastMethod", IsBaseline = false }
        );
        var code = Emitter.Generate(MinimalModel(methods: methods));

        await Assert.That(code).Contains("new global::PicoBench.ComparisonResult(");
        await Assert.That(code).Contains("FastMethod vs BaseMethod");
        await Assert.That(code).Contains("__r_BaseMethod");
        await Assert.That(code).Contains("__r_FastMethod");
    }

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_WithoutBaseline_NoComparisonAdded()
    {
        var methods = ImmutableArray.Create(
            new BenchmarkMethodModel { Name = "MethodA", IsBaseline = false },
            new BenchmarkMethodModel { Name = "MethodB", IsBaseline = false }
        );
        var code = Emitter.Generate(MinimalModel(methods: methods));

        // The declaration of the list always exists, but no comparisons should be added
        await Assert.That(code).DoesNotContain("__comparisons.Add(");
    }

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_BaselineNotComparedAgainstItself()
    {
        var methods = ImmutableArray.Create(
            new BenchmarkMethodModel { Name = "BaseMethod", IsBaseline = true },
            new BenchmarkMethodModel { Name = "Other", IsBaseline = false }
        );
        var code = Emitter.Generate(MinimalModel(methods: methods));

        // Should not contain "BaseMethod vs BaseMethod"
        await Assert.That(code).DoesNotContain("BaseMethod vs BaseMethod");
    }

    // ─── GlobalSetup / GlobalCleanup ────────────────────────────────

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_WithGlobalSetup_CallsSetupMethod()
    {
        var code = Emitter.Generate(
            MinimalModel(globalSetup: new LifecycleMethodInfo { Name = "Setup" })
        );

        await Assert.That(code).Contains("this.Setup();");
    }

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_WithGlobalCleanup_CallsCleanupMethod()
    {
        var code = Emitter.Generate(
            MinimalModel(globalCleanup: new LifecycleMethodInfo { Name = "Cleanup" })
        );

        await Assert.That(code).Contains("this.Cleanup();");
    }

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_WithoutSetupCleanup_NoSetupCleanupCalls()
    {
        var code = Emitter.Generate(MinimalModel());

        // Ensure there's no stray "this.Setup" or "this.Cleanup" injected
        await Assert.That(code).DoesNotContain("this.Setup()");
        await Assert.That(code).DoesNotContain("this.Cleanup()");
    }

    // ─── IterationSetup / IterationCleanup ──────────────────────────

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_WithIterationSetup_PassesSetupDelegate()
    {
        var code = Emitter.Generate(
            MinimalModel(iterSetup: new LifecycleMethodInfo { Name = "IterSetup" })
        );

        await Assert.That(code).Contains("setup: (global::System.Action)(() => this.IterSetup())");
    }

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_WithIterationCleanup_PassesTeardownDelegate()
    {
        var code = Emitter.Generate(
            MinimalModel(iterCleanup: new LifecycleMethodInfo { Name = "IterCleanup" })
        );

        await Assert
            .That(code)
            .Contains("teardown: (global::System.Action)(() => this.IterCleanup())");
    }

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_WithIterationSetupOnly_TeardownIsNull()
    {
        var code = Emitter.Generate(
            MinimalModel(
                iterSetup: new LifecycleMethodInfo { Name = "IterSetup" },
                iterCleanup: null
            )
        );

        await Assert.That(code).Contains("teardown: null");
    }

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_WithIterationCleanupOnly_SetupIsNull()
    {
        var code = Emitter.Generate(
            MinimalModel(
                iterSetup: null,
                iterCleanup: new LifecycleMethodInfo { Name = "IterCleanup" }
            )
        );

        await Assert.That(code).Contains("setup: null");
    }

    // ─── Params ─────────────────────────────────────────────────────

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_WithParams_GeneratesForeachLoop()
    {
        var paramsProps = ImmutableArray.Create(
            new ParamsPropertyModel
            {
                Name = "N",
                TypeFullName = "int",
                FormattedValues = ImmutableArray.Create("10", "100", "1000"),
            }
        );
        var code = Emitter.Generate(MinimalModel(paramsProps: paramsProps));

        await Assert.That(code).Contains("foreach (var __p_N in new int[] { 10, 100, 1000 })");
        await Assert.That(code).Contains("this.N = __p_N;");
    }

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_WithParams_GeneratesParamLabel()
    {
        var paramsProps = ImmutableArray.Create(
            new ParamsPropertyModel
            {
                Name = "Size",
                TypeFullName = "int",
                FormattedValues = ImmutableArray.Create("5"),
            }
        );
        var code = Emitter.Generate(MinimalModel(paramsProps: paramsProps));

        await Assert.That(code).Contains("var __paramLabel = $\"Size={__p_Size}\";");
    }

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_WithMultipleParams_GeneratesNestedLoops()
    {
        var paramsProps = ImmutableArray.Create(
            new ParamsPropertyModel
            {
                Name = "N",
                TypeFullName = "int",
                FormattedValues = ImmutableArray.Create("10", "100"),
            },
            new ParamsPropertyModel
            {
                Name = "Mode",
                TypeFullName = "string",
                FormattedValues = ImmutableArray.Create("\"fast\"", "\"slow\""),
            }
        );
        var code = Emitter.Generate(MinimalModel(paramsProps: paramsProps));

        await Assert.That(code).Contains("foreach (var __p_N in new int[]");
        await Assert.That(code).Contains("foreach (var __p_Mode in new string[]");
        await Assert.That(code).Contains("this.N = __p_N;");
        await Assert.That(code).Contains("this.Mode = __p_Mode;");
    }

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_WithParams_MethodNameIncludesParamLabel()
    {
        var paramsProps = ImmutableArray.Create(
            new ParamsPropertyModel
            {
                Name = "N",
                TypeFullName = "int",
                FormattedValues = ImmutableArray.Create("10"),
            }
        );
        var code = Emitter.Generate(MinimalModel(paramsProps: paramsProps));

        await Assert.That(code).Contains("$\"DoWork [{__paramLabel}]\"");
    }

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_WithoutParams_MethodNameIsLiteral()
    {
        var code = Emitter.Generate(MinimalModel());

        await Assert.That(code).Contains("\"DoWork\"");
    }

    // ─── Combined scenario ──────────────────────────────────────────

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_FullModel_ContainsAllExpectedParts()
    {
        var methods = ImmutableArray.Create(
            new BenchmarkMethodModel { Name = "Baseline", IsBaseline = true },
            new BenchmarkMethodModel { Name = "Candidate", IsBaseline = false }
        );
        var paramsProps = ImmutableArray.Create(
            new ParamsPropertyModel
            {
                Name = "N",
                TypeFullName = "int",
                FormattedValues = ImmutableArray.Create("10", "100"),
            }
        );
        var code = Emitter.Generate(
            MinimalModel(
                ns: "My.Namespace",
                description: "Full test",
                globalSetup: new LifecycleMethodInfo { Name = "Setup" },
                globalCleanup: new LifecycleMethodInfo { Name = "Cleanup" },
                iterSetup: new LifecycleMethodInfo { Name = "IterSetup" },
                iterCleanup: new LifecycleMethodInfo { Name = "IterCleanup" },
                methods: methods,
                paramsProps: paramsProps
            )
        );

        await Assert.That(code).Contains("namespace My.Namespace");
        await Assert.That(code).Contains("this.Setup();");
        await Assert.That(code).Contains("this.Cleanup();");
        await Assert.That(code).Contains("setup: (global::System.Action)(() => this.IterSetup())");
        await Assert
            .That(code)
            .Contains("teardown: (global::System.Action)(() => this.IterCleanup())");
        await Assert.That(code).Contains("foreach (var __p_N in new int[] { 10, 100 })");
        await Assert.That(code).Contains("Candidate vs Baseline");
        await Assert.That(code).Contains("description: \"Full test\"");
    }

    // ─── Suite metadata ─────────────────────────────────────────────

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_EnvironmentInfo_IncludesExecutionModeDetection()
    {
        var code = Emitter.Generate(MinimalModel());

        await Assert.That(code).Contains("ExecutionMode");
        await Assert.That(code).Contains("#if NET8_0_OR_GREATER");
        await Assert.That(code).Contains("RuntimeFeature.IsDynamicCodeSupported");
    }

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_SuiteNameMatchesClassName()
    {
        var code = Emitter.Generate(MinimalModel(className: "MyBench"));

        await Assert.That(code).Contains("\"MyBench\"");
    }

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_UsesStopwatch()
    {
        var code = Emitter.Generate(MinimalModel());

        await Assert.That(code).Contains("global::System.Diagnostics.Stopwatch.StartNew()");
        await Assert.That(code).Contains("__sw.Stop()");
        await Assert.That(code).Contains("__sw.Elapsed");
    }

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_CreatesEnvironmentInfo()
    {
        var code = Emitter.Generate(MinimalModel());

        await Assert.That(code).Contains("new global::PicoBench.EnvironmentInfo");
    }

    // ─── Sync class generation ─────────────────────────────────────

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_SyncClass_ReturnsValueTaskFromResult()
    {
        var code = Emitter.Generate(MinimalModel());

        await Assert.That(code).Contains("ValueTask.FromResult(__suite)");
        await Assert.That(code).DoesNotContain("async ValueTask");
        await Assert.That(code).DoesNotContain("await ");
    }

    // ─── Async class generation ────────────────────────────────────

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_AsyncClass_IsAsyncMethod()
    {
        var methods = ImmutableArray.Create(
            new BenchmarkMethodModel { Name = "WorkAsync", IsAsync = true }
        );
        var model = MinimalModel(
            methods: methods,
            isAsync: true,
            globalSetup: new LifecycleMethodInfo { Name = "Setup", IsAsync = true },
            globalCleanup: new LifecycleMethodInfo { Name = "Cleanup", IsAsync = false }
        );
        var code = Emitter.Generate(model);

        await Assert.That(code).Contains("async global::System.Threading.Tasks.ValueTask");
        await Assert.That(code).Contains("await this.Setup();");
        await Assert.That(code).Contains("this.Cleanup();");
        await Assert.That(code).Contains("await global::PicoBench.Benchmark.RunAsync");
    }

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_AsyncClassWithSyncBenchmark_WrapsInAsyncLambda()
    {
        var methods = ImmutableArray.Create(
            new BenchmarkMethodModel { Name = "SyncWork", IsAsync = false }
        );
        var model = MinimalModel(methods: methods, isAsync: true);
        var code = Emitter.Generate(model);

        await Assert.That(code).Contains("async () => { this.SyncWork(); }");
    }

    [Test]
    [Property("Category", "Emitter")]
    public async Task Generate_AsyncClassWithAsyncIterSetup_WrapsCorrectly()
    {
        var methods = ImmutableArray.Create(
            new BenchmarkMethodModel { Name = "Bench", IsAsync = true }
        );
        var model = MinimalModel(
            methods: methods,
            isAsync: true,
            iterSetup: new LifecycleMethodInfo { Name = "IterSetup", IsAsync = true },
            iterCleanup: new LifecycleMethodInfo { Name = "IterCleanup", IsAsync = false }
        );
        var code = Emitter.Generate(model);

        await Assert.That(code).Contains("setup: async () => { await this.IterSetup(); }");
        await Assert.That(code).Contains("teardown: async () => { this.IterCleanup(); }");
    }
}
